version: '3.8'

services:
  app:
    image: docker_compose:1.2
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - appnet

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: logindb
    ports:  
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appnet

volumes:
  mysql-data:

networks:
  appnet:
