pipeline{
    agent any
    tools{
        maven 'maven-3.9'
    }

    stages{
        stage("build jar"){
            steps{
                
                    script{
                        sh 'mvn package'
                    }
                
            }
        }
        stage("build image"){
            steps{
                script{
                    echo "Building the docker image..."
                    withCredentials([usernamePassword(
                    credentialsId: 'dockerhub_credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )])
                {
                    echo "bulding the docker image..."
                    sh 'docker build -t salman14/salman14_helloworld .'
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push salman14/salman14_helloworld'
                } 
                }
            }
        }
        stage("deploy"){
            steps{
                script{
                    echo "deploying the application..."
                }
            }
        }
    }
}