pipeline{
    agent any
    tools{
        maven 'maven-3.9'
    }

    stages{
        stage("build jar"){
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-17'
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            steps{
                sh 'mvn --version'
            }
        }
        stage("build image"){
            steps{
                script{
                    echo "Building the docker image..."
                    withCredentials([usernamePassword(
                    credentialsId: 'dockerhub_credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )])
                {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                } 
                }
            }
        }
    }
}