def gv // declare at top-level so all stages can use it

pipeline {
    agent any
    stages {
        stage("init") {
            steps {
                script {
                    def filePath = "/home/salman/Documents/salman/dev_ops/Jenkins/script.groovy"
                    if (fileExists(filePath)) {
                        gv = load filePath
                    } else {
                        echo "⚠ ${filePath} not found, skipping load"
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    echo "building the app"
                    gv.build() // example usage
                }
            }
        }
        stage('Test') {
            steps {
                echo "testing the app"
            }
        }
        stage('Deploy') {
            steps {
                echo "deploying the app"
            }
        }
    }
}
