def gv
pipeline {
    agent any
    stages {
        stage("init"){
            steps{
                script{
                    def filePath = "./script.groovy"
                    if (fileExists(filePath)) {
                        gv = load filePath
                    } else {
                        echo "⚠ ${filePath} not found, skipping load"
                    }
                }
            }
        }
        stage('Build') {
            steps {
                echo "building the app"
            }
        }
        stage('Test') {
            steps {
               echo "testing the app"
            }
        }
        stage('Deploy') {
            steps {
                echo "deploying the app"
            }
        }
    }
}
